### ISSUE TITLE
The sagittal T2w and axial MT data are not within the same referential system

### ISSUE THREAD

**Issue by jcohenadad** [ctsmith94/MTR_Project#1]
### Context

The sagittal T2w and axial MT data are not within the same referential system. The image below shows a clear shift in the Z direction between the two images:
![anim](https://user-images.githubusercontent.com/2482071/100477223-b511f980-30b5-11eb-85d0-2a32538f60c0.gif)

This is caused by the two images _not_ being acquired back-to-back within the same session, but across 2 separate sessions (and 2 different scanners).

This is a problem for co-registration, because the algorithm assumes that the z-location does not change between the 2 images. 

### Possible solution

My recommendation would be to not use the T2w image and label vertebrae directly on the MT data. 
- Pros:
  - This removes a step which is prone to error (the T2w has thick slices, which is bad for cord segmentation)
  - Processing will be much faster
- Cons:
  - If MT data are not centered in a particular anatomical landmark, then this solution adds a manual step (manually label intervertebral disc).

@ctsmith94 were the MT data systematically acquired with a particular FOV placement, e.g. center FOV at disc C4-C5?  If not, then a manual step will be required (quick though: about 10s per subject).

**Comment by ctsmith94** [comment]
@jcohenadad no, there was no systematic FOV placement so the manual step will be required

**Comment by jcohenadad** [comment]
now fixed with the new manual procedure
